### ISSUE TITLE
Couldn't load 1.9/redcloth_scan in windows

### ISSUE THREAD

**Issue by marcialwushu** [FGF-College-Work/Forum#103]
````

C:\Users\carlosjunior\Documents\Workspace\CONFERENCE\conference\bin>rails generate open_conference_ware
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/RedCloth-4.3.2/lib/RedCloth.rb:13:in `require': cannot load such file -- 2.4/redcloth_scan (LoadError)
Couldn't load 2.4/redcloth_scan
The $LOAD_PATH was:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-4.0.2/lib/action_view/vendor/html-scanner
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/turbolinks-5.2.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.2.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13-x64-mingw32/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sdoc-1.0.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/open_conference_ware-1.0.0.pre1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/vpim-13.11.11/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/uglifier-4.1.18/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sass-rails-4.0.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sass-3.2.19/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rinku-2.0.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/rinku-2.0.4
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rails-observers-0.1.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rails-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sprockets-rails-2.0.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sprockets-2.12.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tilt-1.4.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-2.2.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ttfunk-1.5.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pdf-core-0.7.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paperclip-4.3.7/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/omniauth-1.1.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.4-x64-mingw32/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mini_portile2-2.3.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mimemagic-0.3.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jquery-rails-3.1.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jbuilder-1.5.3/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hike-1.2.3/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hashie-2.1.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hashery-2.1.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gchartrb-0.8/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dynamic_form-1.1.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/dalli-2.7.8/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/comma-3.2.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/color-1.8/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/coffee-rails-4.0.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/coffee-script-2.4.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/coffee-script-source-1.12.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocaine-0.5.8/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/climate_control-0.2.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/acts-as-taggable-on-4.0.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/arel-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-deprecated_finders-1.0.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activemodel-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionmailer-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mail-2.5.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/treetop-1.4.15/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mime-types-1.25.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-test-0.6.3/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-1.5.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/builder-3.1.4/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-4.0.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-0.3.54/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thread_safe-0.3.6/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multi_json-1.13.1/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-4.7.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/i18n-0.9.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aasm-5.0.0/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/RedCloth-4.3.2/lib
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/RedCloth-4.3.2/lib/case_sensitive_require
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/RedCloth-4.3.2/ext
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/RedCloth-4.3.2
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/x64-msvcrt
C:/Ruby24-x64/lib/ruby/site_ruby
C:/Ruby24-x64/lib/ruby/vendor_ruby/2.4.0
C:/Ruby24-x64/lib/ruby/vendor_ruby/2.4.0/x64-msvcrt
C:/Ruby24-x64/lib/ruby/vendor_ruby
C:/Ruby24-x64/lib/ruby/2.4.0
C:/Ruby24-x64/lib/ruby/2.4.0/x64-mingw32
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/RedCloth-4.3.2/lib/RedCloth.rb:13:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/open_conference_ware-1.0.0.pre1/lib/open_conference_ware/dependencies.rb:10:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/open_conference_ware-1.0.0.pre1/lib/open_conference_ware/dependencies.rb:10:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/open_conference_ware-1.0.0.pre1/lib/open_conference_ware.rb:1:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/open_conference_ware-1.0.0.pre1/lib/open_conference_ware.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `block in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler.rb:114:in `require'
        from C:/Users/carlosjunior/Documents/Workspace/CONFERENCE/conference/config/application.rb:7:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-4.0.2/lib/rails/commands.rb:43:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-4.0.2/lib/rails/commands.rb:43:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>' 

````

**Comment by marcialwushu** [comment]
Install OpenConferenceWare's configuration files and seed data:

```
 $ bin/rails generate open_conference_ware:install

```

I then opened the file ```c:\Ruby192\lib\ruby\gems\1.9.1\gems\RedCloth-4.2.8\lib\redcloth.rb```, don't know why still, does it complain a folder (maybe ```C:\Ruby192\lib\ruby\gems\1.9.1\gems\RedCloth-4.2.8\ext\redcloth_scan```) not found?, so paste the code snippets here:

```

require 'rbconfig'
begin
  prefix = Config::CONFIG['arch'] =~ /mswin|mingw/ ? "#{Config::CONFIG['MAJOR']}.#{Config::CONFIG['MINOR']}/" : ''
  lib = "#{prefix}redcloth_scan"
  require lib
rescue LoadError => e
  e.message << %{\nCouldn't load #{lib}\nThe $LOAD_PATH was:\n#{$LOAD_PATH.join("\n")}}
  raise e
end

```

**Comment by marcialwushu** [comment]
```

*** LOCAL GEMS ***

aasm (5.0.0)
actionmailer (4.0.2)
actionpack (4.0.2)
activemodel (4.0.2)
activerecord (4.0.2)
activerecord-deprecated_finders (1.0.4)
activesupport (4.0.2)
acts-as-taggable-on (4.0.0)
arel (4.0.2)
bigdecimal (default: 1.3.2)
builder (3.1.4)
bundler (1.16.4)
climate_control (0.2.0)
cocaine (0.5.8)
coffee-rails (4.0.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
color (1.8)
comma (3.2.4)
concurrent-ruby (1.0.5)
dalli (2.7.8)
did_you_mean (1.1.0)
dynamic_form (1.1.4)
erubis (2.7.0)
execjs (2.7.0)
gchartrb (0.8)
hashery (2.1.2)
hashie (2.1.2)
hike (1.2.3)
i18n (0.9.5)
io-console (default: 0.4.6)
jbuilder (1.5.3)
jquery-rails (3.1.5)
json (default: 2.0.4)
mail (2.5.5)
mime-types (1.25.1)
mimemagic (0.3.0)
mini_portile2 (2.3.0)
minitest (5.10.1, 4.7.5)
multi_json (1.13.1)
net-telnet (0.1.1)
nokogiri (1.8.4 x64-mingw32)
omniauth (1.1.4)
open_conference_ware (1.0.0.pre1)
openssl (default: 2.0.7)
paperclip (4.3.7)
pdf-core (0.7.0)
polyglot (0.3.5)
power_assert (0.4.1)
prawn (2.2.2)
psych (default: 2.2.2)
rack (1.5.5)
rack-test (0.6.3)
rails (4.0.2)
rails-observers (0.1.5)
railties (4.0.2)
rake (12.3.1, 12.0.0)
rdoc (6.0.4, default: 5.0.0)
RedCloth (4.3.2)
rinku (2.0.4)
sass (3.2.19)
sass-rails (4.0.5)
sdoc (1.0.0)
sprockets (2.12.5)
sprockets-rails (2.0.1)
sqlite3 (1.3.13 x64-mingw32)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (1.4.1)
treetop (1.4.15)
ttfunk (1.5.1)
turbolinks (5.2.0)
turbolinks-source (5.2.0)
tzinfo (0.3.54)
uglifier (4.1.18)
vpim (13.11.11)
xmlrpc (0.2.1)

```

**Comment by marcialwushu** [comment]
```
>ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]

```
