### ISSUE TITLE
MIRTH CONNECT README

### ISSUE THREAD

**Issue by marcialwushu** [FGF-College-Work/Forum#116]
MIRTH CONNECT README

Contents
==================================================

1. General Information
2. Installation and Upgrade
3. Starting Mirth Connect
4. Running Mirth Connect in Java 9 or greater
5. More Information

## 1. General Information
==================================================

Mirth Connect is an open source health care integration engine. By supporting numerous standards (like HL7, EDI/X12, XML, NCPDP, DICOM, and Delimited Text) and protocols (like TCP/LLP, HTTP, JDBC, and File/FTP/SFTP), Mirth Connect allows for the filtering, transformation, and routing of messages between disparate systems to allow them to share data.

## 2. Installation and Upgrade
==================================================

Mirth Connect installers are available for individual operating systems (EXE for Windows, RPM and SH for Linux, and DMG for Mac OS X). Pre-packaged distributions are also available for individual operating systems (ZIP for Windows, TAR.GZ for Linux, and TAR.GZ for Mac OS X). The installer allows you to automatically upgrade previous Mirth Connect installations (starting with version 1.5).

Mirth Connect installers also come with the option to install and start a service which will run the background. You also have the option of installing and running the Mirth Connect Server Manager, which allows you to start and stop the service on some operating systems, change Mirth Connect properties and backend database settings, and view the server logs.

An optional Mirth Connect Command Line Interface can be installed, allowing you to connect to a running Mirth Connect Server using a command line. This tool is useful for performing or scripting server tasks without opening the Mirth Connect Administrator.

After the installation, the Mirth Connect directory layout will look as follows:

/appdata/mirthdb: The embedded database (Do NOT delete if you specify Derby as your database). This will be created when the Mirth Connect Server is started. The path for appdata is defined by the dir.appdata property in mirth.properties.
/cli-lib: Libraries for the Mirth Connect Command Line Interface (if installed)
/client-lib: Libraries for the Mirth Connect Administrator
/conf: Configuration files
/custom-lib: Place your custom user libraries here. These libraries will be loaded on the Mirth Connect Server classpath when it is started, making them accessible to channel scripts.
/docs: This document and a copy of the Mirth Connect license
/docs/javadocs: Generated javadocs for the installed version of Mirth Connect. These documents are also available when the server is running at http://[server address]:8080/javadocs/ (i.e. http://localhost:8080/javadocs/).
/extensions: Libraries and meta data for Plug-ins and Connectors
/logs: Default location for logs generated by Mirth Connect and its sub-components
/manager-lib: Libraries for the Mirth Connect Server Manager (if installed)
/public_html: Directory exposed by the embedded web server
/server-lib: Mirth Connect server libraries
/webapps: Directory exposed by the embedded web server to host webapps

## 3. Starting Mirth Connect
==================================================

Once Mirth Connect has been installed, there are several ways to connect to launch the Mirth Connect Administrator. On a Windows installation, there is a Mirth Connect Administrator item in the Start Menu which launches the application directly.

If the option is not available, you can connect to the Mirth Connect Administrator launch page which by default should be available at http://[server address]:8080 (i.e. http://localhost:8080). Clicking the Launch Mirth Connect Administrator button will connect you to the server which will be listening on https://[server address]:8443 (i.e. https://localhost:8443). If running a new installation, the default username and password for the login screen is admin and admin. This should be changed immediately for security purposes.

If you are launching the administrator for the first time, you will notice that the libraries for the Mirth Connect Administrator will be loaded. This feature allows you run the Administrator from any remote Mirth Connect server without having to download and install a separate client.

You may also notice a security warning when starting the administrator (dialog box depends on browser being used). This is normal and you should click Run to continue launching the administrator.

## 4. Running Mirth Connect in Java 9 or greater
==================================================

In order to run Mirth Connect in Java 9 or greater, copy the options from /docs/mcservice-java9+.vmoptions and append them to either mcserver.vmoptions or mcservice.vmoptions, depending on your deployment. Then restart Mirth Connect.

To run the Mirth Connect Command Line Interface, create a new file named mccommand.vmoptions in the Mirth Connect root directory. Copy all of the options from /docs/mcservice-java9+.vmoptions into mccommand.vmoptions and save before launching the Command Line Interface.

## 5. More Information
==================================================

You can find the latest Mirth Connect release information, documentation, and more at: http://www.mirthcorp.com

Join the Mirth Community at: http://www.mirthcorp.com/community/registration

**Comment by marcialwushu** [comment]
## Adminstrator Launcher 1.0.0 Released

As some of you may know by now, Oracle has removed Java Web Start starting in Java 11. You won't necessarily need to worry about this until you start using Java 11, and support for 11 will be coming with Connect 3.7. But in the meantime, we're releasing this product ahead of time to get feedback from the community! 

 This is a standalone application that you install on your local workstation, and allows you to remotely launch the Administrator GUI for any NextGen Connect server you want. It completely replaces Java Web Start, so no more Java cache issues! 

 All versions of Mirth/NextGen Connect are supported, all the way back to 2.x.  You don't even need to have Java installed on your local workstation anymore, as this application comes with a Java 8 Runtime Environment built-in!  

Go to our Downloads page and download the Administrator Launcher installer for your operating system. After installing, you can create and manage multiple NextGen Connect server connections in a single place!  

Here's a sample screenshot: https://i.imgur.com/pUeIZdt.png  

If you choose to associate JNLP files in the installation process, opening that "webstart.jnlp" file will automatically use the new Administrator Launcher! You can also set your internet browser to automatically open JNLP files with the Administrator Launcher as well.  

Give it a try, and let us know what you think! We have a discussion thread for this up on our forums here.

**Comment by marcialwushu** [comment]
# Mirth Connect 3.6.1

Mirth Connect 3.6.1 is a patch release containing a few bug fixes.  Some key features and benefits of 3.6 include:

- FHIR Connector Extension — In addition to updating our FHIR extension to support STU3 (R3), we've added a number of other enhancements as well! There's a new FHIR Sender destination you can use to connect to external FHIR servers. A new FHIR data type supports both XML and JSON resources simultaneously. A new graphical UI builder for resources is available on the FHIR Sender, as well as on a new transformer step type and code template type. An updated user guide and lots of examples (for instance, how to convert HL7 v2.x to FHIR) are available on the public wiki!
 
- Interoperability Connector Suite — This is a completely new commercial extension that provides Listener and Sender connectors that can help kickstart your eHealth Exchange / Sequoia onboarding and integration. The connectors support the most common operations for PIX, PDQ, XDS.b, XCA, and XCPD. They also support automatic generation and validation of NHIN-compliant SAML/WS-Security sections. In addition, the suite provides a new resource that automatically downloads and syncs business endpoint information from a UDDI Provider!
 
- Multi-Factor Authentication — This commercial extension is new as of 3.5.2, and provides an extra security layer for all user accounts! A secondary device such as a phone, tablet, or landline is used to ensure that no one but the actual user can login, even if they know the correct username and password. Both Duo and generic apps such as Google Authenticator / Authy are supported. When using Duo, advanced options such as lockout protection, automatic enrollment, and policy management are available in the Duo administrator dashboard.
 
- Advanced Clustering Enhancements — View and manage alerts, server logs, connection logs, and global maps across the entire cluster! Automatically prune old, offline server IDs. Global Scripts now auto-compile across the entire cluster. Reload Resources now executes across the entire cluster. More information on our Advanced Clustering commercial extension here!
 
- Amazon S3 support for File Reader/Writer — Both the File Reader and File Writer now support Amazon S3! Set explicit AWS credentials, or use the Default Credential Provider Chain to automatically lookup credentials from a variety of common locations. Temporary credentials are supported as well via the Amazon Security Token Service (STS). You can also supply custom headers for PUT requests, including encryption settings and custom object metadata!
 
- And More!

**Comment by marcialwushu** [comment]
Log Information 

```java

[2018-11-17 09:07:15,500]  ERROR  (com.mirth.connect.connectors.jdbc.DatabaseReceiver:131): Failed to poll for messages from the database in channel "SQLConnect2018"
com.mirth.connect.connectors.jdbc.DatabaseReceiverException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM SELECT FROM SELECT * FROM `ccda_components` WHERE 1' at line 2
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverQuery.poll(DatabaseReceiverQuery.java:219)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:111)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM SELECT FROM SELECT * FROM `ccda_components` WHERE 1' at line 2
	at jdk.internal.reflect.GeneratedConstructorAccessor85.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1062)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2758)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2826)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverQuery.poll(DatabaseReceiverQuery.java:190)
	... 4 more

```

**Comment by marcialwushu** [comment]
```error

[2018-11-17 09:51:40,091]  ERROR  (com.mirth.connect.connectors.jdbc.DatabaseReceiverQuery:290): An error occurred while executing the post-process SQL, retrying
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' date = , encounter = , form_name = , form_id = , pid = , user = , groupname = ,' at line 2
	at jdk.internal.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1062)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2758)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2826)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1302)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverQuery.runUpdateStatement(DatabaseReceiverQuery.java:280)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverQuery.afterPoll(DatabaseReceiverQuery.java:248)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:140)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)


```

**Comment by marcialwushu** [comment]
```xml

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<result>
    <created_time>2018-11-18 01:30:00.0</created_time>
    <amendment_note>New amendment request Approved</amendment_note>
    <amendment_id>2</amendment_id>
    <amendments_history_created_by>1</amendments_history_created_by>
    <amendment_status>approved</amendment_status>
</result>
```
