### ISSUE TITLE
ERROR TypeError: Cannot read property 'getWiFiIPAddress' of undefined

### ISSUE THREAD

**Issue by marcialwushu** [FGF-College-Work/Forum#65]
```
TypeError: Cannot read property 'getWiFiIPAddress' of undefined
    at HomePage.webpackJsonp.196.HomePage.getIpAdress (http://localhost:8100/build/main.js:91:26)
    at Object.eval [as handleEvent] (ng:///AppModule/HomePage.ngfactory.js:45:31)
    at handleEvent (http://localhost:8100/build/vendor.js:13921:155)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15430:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:15017:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10336:25)
    at http://localhost:8100/build/vendor.js:10961:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:39436:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5114:33)
```

**Comment by marcialwushu** [comment]
https://github.com/salbahra/cordova-plugin-networkinterface


First install the wrapper:

```
npm install @ionic-native/network-interface

```
Define it in your modules:

```
import { NetworkInterface } from '@ionic-native/network-interface';

@NgModule( {
    ...
    providers: [
        NetworkInterface
    ],
} )

```

Then use it as follows:

```
import { NetworkInterface } from '@ionic-native/network-interface';

constructor( private networkInterface: NetworkInterface ) {
    this.networkInterface.getWiFiIPAddress( ip => alert( ip ) );
    this.networkInterface.getCarrierIPAddress( ip => alert( ip ) );
}

```
