### ISSUE TITLE
Packager not loading React Native Expo

### ISSUE THREAD

**Issue by marcialwushu** [FGF-College-Work/Forum#97]
# Packager not loading React Native Expo

npm start --verbose

```

npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\carlosjunior\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'start',
npm verb cli   '--verbose' ]
npm info using npm@6.4.0
npm info using node@v8.11.2
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle BeachListCeara@0.1.0~prestart: BeachListCeara@0.1.0
npm info lifecycle BeachListCeara@0.1.0~start: BeachListCeara@0.1.0

> BeachListCeara@0.1.0 start C:\Users\carlosjunior\Documents\Workspace\React\ReactNativeBeachListCeara
> react-native-scripts start

15:50:17: Starting packager...

```

And…1/ 20 / 30 minutes later it’s still there…

**Comment by marcialwushu** [comment]
Ok. It was fixed by runnig

```
sudo sysctl -w fs.inotify.max_user_watches=10000

```

before “npm start”

**Comment by marcialwushu** [comment]
https://forums.expo.io/t/packager-not-loading-on-linux/2034

**Comment by marcialwushu** [comment]
https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

**Comment by marcialwushu** [comment]
```

>exp publish
[16:37:53] Unable to find an existing exp instance for this directory, starting a new one...
[16:38:18] Starting Metro Bundler on port 19001.
[16:38:18] Metro Bundler ready.
[16:38:24] Publishing to channel 'default'...
[16:38:24] An Expo user account is required to proceed.
? How would you like to authenticate?
? How would you like to authenticate? Log in with an existing Expo account
? Username/Email Address: ******
? Username/Email Address: ******
? Password: [input is hidden] ******
? Password: [hidden]

Success. You are now logged in as cleilson.
[16:40:30] Building iOS bundle
[16:40:31] 500 - "{\"type\":\"TransformError\",\"lineNumber\":0,\"errors\":[{\"description\":\"C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\react-native-scripts\\\\build\\\\bin\\\\crna-entry.js: Plugin/Preset files are not allowed to export objects, only functions. In C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\babel-preset-expo\\\\index.js\",\"lineNumber\":0}],\"name\":\"SyntaxError\",\"message\":\"C:\\\\Users\\\\carlosjunior\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\react-native-scripts\\\\build\\\\bin\\\\crna-entry.js: Plugin/Preset files are not allowed to export objects, only functions. In C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\babel-preset-expo\\\\index.js\",\"stack\":\"Error: Plugin/Preset files are not allowed to export objects, only functions. In C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\babel-preset-expo\\\\index.js\\n    at createDescriptor (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:162:11)\\n    at items.map (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:87:50)\\n    at Array.map (<anonymous>)\\n    at createDescriptors (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:87:29)\\n    at createPresetDescriptors (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:79:10)\\n    at presets (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:61:19)\\n    at presets (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:51:25)\\n    at mergeChainOpts (C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-chain.js:308:26)\\n    at C:\\\\Users\\\\marcialwushu\\\\Documents\\\\Workspace\\\\React\\\\ReactNativeBeachListCeara\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-chain.js:271:7\"}"
[16:40:31] Set EXPO_DEBUG=true in your env to view the stack trace.
Building JavaScript bundle [

```

**Comment by marcialwushu** [comment]
Does anybody knows why when running the packager, it hangs on

r$ npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ ‘/usr/bin/nodejs’, ‘/usr/bin/npm’, ‘start’, ‘–verbose’ ]
npm info using npm@4.2.0
npm info using node@v7.10.1
npm verb run-script [ ‘prestart’, ‘start’, ‘poststart’ ]
npm info lifecycle Reader@0.0.1~prestart: Reader@0.0.1
npm info lifecycle Reader@0.0.1~start: Reader@0.0.1

Reader@0.0.1 start /home/kimi/test/ExpoApp
react-native-scripts start

1:38:06 PM: Starting packager…

And…1/ 20 / 30 minutes later it’s still there…

Thanks!
